# Utilisation d'une image Python 3.8
FROM python:3.8

# Définition de l'environnement de travail
WORKDIR /usr/src/app

# Installation des dépendances
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copie du code de l'application
COPY . .

# Exposition du port 8000
EXPOSE 8000

# Commande pour démarrer l'application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]